### ISSUE TITLE
Inference Process and Training

### ISSUE THREAD

**Issue by xdwang0726** [ZNLP/NCLS-Corpora#3]
Hi, 

I am wondering is your training process and inference processing are the same when using greedy search? Thank you!

**Comment by Zhujunnan** [comment]
Hi, 
Whether using beam search or greedy search, the training and inference process are inconsistent, because the training conducts the teacher-forcing while the inference takes the decoded output from the previous moment as the input for the next step.

In our multi-task models, during the inference step, we only focus on the output of the cross-lingual summarization decoder, while the output of the other decoder is directly ignored. Thus during inference, we only need to feed the cross-lingual summarization dataset into the model, while we don't care about the text that the other decoder (machine translation or monolingual summarization) needs to decode.

I hope the above can be helpful to you.

Best regards!
